# Generated by Django 5.0.4 on 2024-06-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="filepath",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
