# Generated by Django 5.0.4 on 2024-07-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_data_filepath"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="data",
            name="is_viewable",
        ),
        migrations.AddField(
            model_name="data",
            name="image_link",
            field=models.TextField(blank=True, null=True),
        ),
    ]
