# Generated by Django 5.0.4 on 2024-07-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_data_is_viewable_data_image_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="size_in_mb",
            field=models.FloatField(blank=True, null=True, verbose_name="Size (MB)"),
        ),
        migrations.AlterField(
            model_name="data",
            name="filepath",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Link to Data"
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="image_link",
            field=models.TextField(blank=True, null=True, verbose_name="Image Link"),
        ),
    ]
