# Generated by Django 5.0.4 on 2024-04-19 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_molecule_file_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="data",
            options={"verbose_name_plural": "Data"},
        ),
        migrations.RenameField(
            model_name="data",
            old_name="data",
            new_name="file",
        ),
    ]
