# Generated by Django 5.0.4 on 2024-04-19 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_data_options_rename_data_data_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="band",
            name="disk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bands",
                to="api.disk",
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="molecule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data",
                to="api.molecule",
            ),
        ),
        migrations.AlterField(
            model_name="disk",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disks",
                to="api.region",
            ),
        ),
        migrations.AlterField(
            model_name="molecule",
            name="band",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="molecules",
                to="api.band",
            ),
        ),
    ]
