# Generated by Django 5.0.4 on 2024-07-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_data_size_in_mb_alter_data_filepath_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="disk",
            name="features",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="region",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
