# Generated by Django 5.0.4 on 2024-05-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_band_disk_alter_data_molecule_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CarouselImage",
        ),
        migrations.AlterField(
            model_name="region",
            name="name",
            field=models.CharField(max_length=40),
        ),
    ]
