# Generated by Django 5.0.7 on 2024-07-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_disk_features_region_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disk",
            name="features",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
