# Generated by Django 5.0.4 on 2024-05-24 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("authors", models.CharField(max_length=100)),
                ("full_authors", models.CharField(max_length=100)),
                ("journal_info", models.CharField(max_length=100)),
                ("summary", models.TextField()),
                ("image", models.ImageField(upload_to="publications/")),
                ("pdf_link", models.CharField(max_length=100)),
                ("bibtex_link", models.CharField(max_length=100)),
                ("data_link", models.CharField(max_length=100)),
                ("sao_nasa_link", models.CharField(max_length=100)),
            ],
        ),
    ]
