# Generated by Django 5.0.4 on 2024-06-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_management", "0002_publication"),
    ]

    operations = [
        migrations.CreateModel(
            name="PressNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Press News",
            },
        ),
    ]
