# Generated by Django 5.0.4 on 2024-06-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_management", "0003_pressnews"),
    ]

    operations = [
        migrations.AddField(
            model_name="pressnews",
            name="news_type",
            field=models.CharField(
                choices=[("OP", "Official Press"), ("AN", "AGEPRO in the News")],
                default="OP",
                max_length=2,
            ),
        ),
    ]
