# Generated by Django 5.1.2 on 2025-05-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_management", "0004_pressnews_news_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="authors",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="publication",
            name="bibtex_link",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="publication",
            name="data_link",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="publication",
            name="full_authors",
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name="publication",
            name="pdf_link",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="publication",
            name="sao_nasa_link",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="publication",
            name="title",
            field=models.CharField(max_length=1000),
        ),
    ]
