name: ALMA Backend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      ALLOWED_HOSTS: localhost,127.0.0.1
      DEBUG: "True"

    steps:
      - uses: actions/checkout@v4

      - name: Instalar uv y configurar Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.11"
          enable-cache: true
          cache-dependency-glob: |
            pyproject.toml
            uv.lock

      - name: Instalar dependencias
        run: uv sync --all-extras --dev

      - name: Verificar calidad del código
        run: make quality-check

      - name: Ejecutar pruebas
        run: make test
