name: Deploy Backend (Django)

on:
  push:
    branches:
      - main
    paths:
      - "**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy Backend to Server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          PROJECT_ROOT_ON_SERVER: ${{ secrets.PROJECT_ROOT_ON_SERVER }}
        run: |
          echo "--- Workflow environment variables ---"
          echo "SSH_USER: $SSH_USER"
          echo "SSH_HOST: $SSH_HOST"
          echo "SSH_PORT: $SSH_PORT"
          echo "PROJECT_ROOT_ON_SERVER: $PROJECT_ROOT_ON_SERVER"
          echo "------------------------------------"
          echo "Connecting to $SSH_USER@$SSH_HOST:$SSH_PORT"
          ssh -o StrictHostKeyChecking=no -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" << 'EOF'
            set -e

            echo "Navigating to backend repository: $PROJECT_ROOT_ON_SERVER/backend"
            cd "$PROJECT_ROOT_ON_SERVER/backend"

            echo "Pulling latest backend code..."
            git pull

            echo "Navigating back to docker-compose root: $PROJECT_ROOT_ON_SERVER"
            cd "$PROJECT_ROOT_ON_SERVER"

            echo "Building Django image..."
            docker compose build django

            echo "Restarting Django service..."
            docker compose up -d django

            echo "Running Django migrations..."
            docker compose exec django python manage.py migrate --noinput

            echo "Collecting Django static files..."
            docker compose exec django python manage.py collectstatic --noinput

            echo "Django deployment complete."
          EOF
